//package com.lukas.ramonas.cms.DAO;
//
//import com.lukas.ramonas.cms.Model.User;
//import com.lukas.ramonas.cms.DAO.UserRepository;
//
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.*;
//
//@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
//public class MainController {
//     // This means to get the bean called user_tableRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//
//    @Autowired
//    private UserRepository UserRepository;
//
//    @PostMapping(path="/add") // Map ONLY POST Requests
//    public @ResponseBody String addNewUser (
//            @RequestParam String name,
//            @RequestParam String username,
//            @RequestParam String password,
//            @RequestParam String email,
//            @RequestParam String role,
//            @RequestParam Boolean confirmed) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        User n = new User();
//        n.setName(name);
//        n.setUsername(username);
//        n.setPassword(password);
//        n.setEmail(email);
//        n.setRole(role);
//        n.setConfirmed(confirmed);
//        UserRepository.save(n);
//        return "Saved";
//    }
//
//
////    @GetMapping(path="/all")
////    public @ResponseBody Iterable<User> getAllUsers() {
////        // This returns a JSON or XML with the users
////      //  return UserRepository.findAll();
////    }
//}