package com.lukas.ramonas.cms.DAO;

import com.lukas.ramonas.cms.Model.user_table;
import com.lukas.ramonas.cms.Repository.user_tableRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called user_tableRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private user_tableRepository user_tableRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (
            @RequestParam String name,
            @RequestParam String username,
            @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        user_table n = new user_table();
        n.setName(name);
        n.setUsername(username);
        n.setEmail(email);
        user_tableRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<user_table> getAllUsers() {
        // This returns a JSON or XML with the users
        return user_tableRepository.findAll();
    }
}